### ISSUE TITLE
Erstellen einer Versionierung für Dokumente

### ISSUE THREAD

**Issue by Paul-B-B** [FlorianAlbert/Projekt-Apollon#55]
- [x] Erstellung der Versionierung für Dokumente
- [x] Einfügen der Versionierung in die Word Vorlage
- [x] Einfügen der Versionierung in Recherchebericht
- [x] Einfügen der Versionierung in Lastenheft

**Comment by etienneZink** [comment]
Erster Vorschlag unterbreitet und in Recherchebericht und Vorlage übertragen
